import type { ProductSeed } from "./types"

// ─── Jambons d'Iparralde (6 produits) ────────────────────────────────

const JAMBONS: ProductSeed[] = [
  {
    handle: "jambon-orhi-24-mois",
    title: "Jambon Orhi 24 mois",
    subtitle: "Race Duroc · Iparralde · sans nitrite",
    description:
      "Notre jambon signature. Affiné 24 mois au sel sec de Salies-de-Béarn dans nos caves du Pays Basque. Race Duroc nourrie aux céréales locales, sans nitrite ajouté. Une pièce d'exception, marquée par les saveurs longues de l'affinage prolongé.",
    product_type: "alimentaire",
    shipping_kind: "fresh",
    category_handles: ["jambons-iparralde/orhi-entier", "jambons-iparralde"],
    variants: [
      {
        title: "Entier avec os",
        sku: "ORHI24-ENT-OS",
        price_eur: 320,
        weight_grams: 7500,
        format: "entier_os",
        initial_stock: 8,
      },
      {
        title: "Entier désossé",
        sku: "ORHI24-ENT-DES",
        price_eur: 360,
        weight_grams: 6000,
        format: "entier_desosse",
        initial_stock: 10,
      },
      {
        title: "Demi",
        sku: "ORHI24-DEMI",
        price_eur: 195,
        weight_grams: 3000,
        format: "demi",
        initial_stock: 12,
      },
      {
        title: "Quart",
        sku: "ORHI24-QUART",
        price_eur: 105,
        weight_grams: 1500,
        format: "quart",
        initial_stock: 18,
      },
      {
        title: "Tranches 100g",
        sku: "ORHI24-TR-100",
        price_eur: 12,
        weight_grams: 100,
        format: "tranches_100g",
        initial_stock: 50,
      },
    ],
    details: {
      aging_months: 24,
      origin: "Iparralde",
      breed: "Duroc",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "fresh",
      conservation_days_after_opening: 30,
      ddm_days: 60,
      cure_method: "Sel sec de Salies-de-Béarn",
      nutritional: {
        energy_kcal: 305,
        fat: 19,
        fat_saturated: 7,
        protein: 32,
        salt: 5.2,
      },
      ingredients: "Viande de porc Duroc (98%), sel de Salies-de-Béarn (2%).",
      terroir_story:
        "Orhi est le sommet emblématique d'Iparralde. Nos cochons Duroc paissent dans ses vallées, nourris d'orge et de maïs basques. 24 mois d'affinage en cave naturelle leur donnent une bouche profonde et persistante.",
      pairings_tags: ["patxaran", "piment-espelette", "vin-rouge-irouleguy"],
      seo_title: "Jambon Orhi 24 mois sans nitrite | Race Duroc | Lehena",
      seo_description:
        "Jambon Orhi 24 mois, race Duroc, affiné au sel de Salies-de-Béarn. Sans nitrite. Entier, désossé, demi, quart ou tranches. Livraison Chronofresh.",
      og_image_url: null,
      noindex: false,
    },
  },
  {
    handle: "jambon-orhi-18-mois",
    title: "Jambon Orhi 18 mois",
    subtitle: "Race Duroc · sans nitrite",
    description:
      "Affinage intermédiaire qui équilibre douceur et caractère. Idéal pour découvrir notre signature, ou pour les amateurs qui préfèrent un jambon plus tendre que le 24 mois.",
    product_type: "alimentaire",
    shipping_kind: "fresh",
    category_handles: ["jambons-iparralde/orhi-entier", "jambons-iparralde"],
    variants: [
      {
        title: "Entier avec os",
        sku: "ORHI18-ENT-OS",
        price_eur: 260,
        weight_grams: 7200,
        format: "entier_os",
        initial_stock: 10,
      },
      {
        title: "Entier désossé",
        sku: "ORHI18-ENT-DES",
        price_eur: 295,
        weight_grams: 5800,
        format: "entier_desosse",
        initial_stock: 12,
      },
      {
        title: "Demi",
        sku: "ORHI18-DEMI",
        price_eur: 159,
        weight_grams: 2900,
        format: "demi",
        initial_stock: 15,
      },
      {
        title: "Tranches 100g",
        sku: "ORHI18-TR-100",
        price_eur: 10,
        weight_grams: 100,
        format: "tranches_100g",
        initial_stock: 60,
      },
    ],
    details: {
      aging_months: 18,
      origin: "Iparralde",
      breed: "Duroc",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "fresh",
      conservation_days_after_opening: 30,
      ddm_days: 60,
      cure_method: "Sel sec de Salies-de-Béarn",
      ingredients: "Viande de porc Duroc (98%), sel de Salies-de-Béarn (2%).",
      pairings_tags: ["patxaran", "piment-espelette"],
      seo_title: "Jambon Orhi 18 mois sans nitrite | Lehena",
      seo_description:
        "Jambon Orhi 18 mois affiné, race Duroc, sans nitrite. Entier, désossé, demi ou tranches. Du Pays Basque, livraison Chronofresh.",
      og_image_url: null,
      noindex: false,
    },
  },
  {
    handle: "jambon-orhi-15-mois",
    title: "Jambon Orhi 15 mois",
    subtitle: "Première cuvée · sans nitrite",
    description:
      "Notre première cuvée, généreuse et accessible. Le jambon idéal pour la consommation quotidienne, en sandwich, sur un plat de pâtes ou en planche.",
    product_type: "alimentaire",
    shipping_kind: "fresh",
    category_handles: ["jambons-iparralde/orhi-entier", "jambons-iparralde"],
    variants: [
      {
        title: "Entier avec os",
        sku: "ORHI15-ENT-OS",
        price_eur: 215,
        weight_grams: 7000,
        format: "entier_os",
        initial_stock: 12,
      },
      {
        title: "Demi",
        sku: "ORHI15-DEMI",
        price_eur: 130,
        weight_grams: 2800,
        format: "demi",
        initial_stock: 18,
      },
      {
        title: "Tranches 100g",
        sku: "ORHI15-TR-100",
        price_eur: 8,
        weight_grams: 100,
        format: "tranches_100g",
        initial_stock: 80,
      },
      {
        title: "Tranches 200g",
        sku: "ORHI15-TR-200",
        price_eur: 15,
        weight_grams: 200,
        format: "tranches_200g",
        initial_stock: 40,
      },
    ],
    details: {
      aging_months: 15,
      origin: "Iparralde",
      breed: "Duroc",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "fresh",
      conservation_days_after_opening: 30,
      ddm_days: 60,
      cure_method: "Sel sec de Salies-de-Béarn",
      ingredients: "Viande de porc Duroc (98%), sel de Salies-de-Béarn (2%).",
      seo_title: "Jambon Orhi 15 mois sans nitrite | Lehena",
      seo_description:
        "Jambon Orhi 15 mois, première cuvée Lehena. Race Duroc, sans nitrite, à découvrir entier, demi ou en tranches.",
      og_image_url: null,
      noindex: false,
    },
  },
  {
    handle: "selection-chef-jambon-orhi-24",
    title: "Sélection du Chef · Orhi 24 mois 200g tranches",
    description:
      "Sachet tranché finement de notre Orhi 24 mois, sélectionné par notre maître affineur.",
    product_type: "alimentaire",
    shipping_kind: "fresh",
    category_handles: ["jambons-iparralde/tranches", "jambons-iparralde"],
    variants: [
      {
        title: "Sachet 200g",
        sku: "ORHI24-CHEF-200",
        price_eur: 28,
        weight_grams: 200,
        format: "tranches_200g",
        initial_stock: 60,
      },
    ],
    details: {
      aging_months: 24,
      origin: "Iparralde",
      breed: "Duroc",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "fresh",
      conservation_days_after_opening: 5,
      ddm_days: 35,
      cure_method: "Sel sec de Salies-de-Béarn",
      ingredients: "Viande de porc Duroc (98%), sel de Salies-de-Béarn (2%).",
      seo_title: "Tranches Orhi 24 mois 200g · sélection chef | Lehena",
      seo_description:
        "Sachet de tranches fines Orhi 24 mois, conditionné sous-vide. Affinage long, sans nitrite. Format 200g pratique.",
      og_image_url: null,
      noindex: false,
    },
  },
  {
    handle: "jambon-kintoa-aoc",
    title: "Jambon Kintoa AOC 24 mois",
    subtitle: "Race basque · AOC · sans nitrite",
    description:
      "Élevé en Pays Basque, le porc Kintoa (race locale autrefois menacée d'extinction) bénéficie de l'AOC. Persillage marqué, gras fondant, mâche dense. Une pièce rare.",
    product_type: "alimentaire",
    shipping_kind: "fresh",
    category_handles: ["jambons-iparralde/orhi-entier", "jambons-iparralde"],
    variants: [
      {
        title: "Entier avec os",
        sku: "KINTOA-ENT-OS",
        price_eur: 420,
        weight_grams: 7000,
        format: "entier_os",
        initial_stock: 4,
      },
      {
        title: "Demi",
        sku: "KINTOA-DEMI",
        price_eur: 240,
        weight_grams: 2800,
        format: "demi",
        initial_stock: 6,
      },
      {
        title: "Tranches 100g",
        sku: "KINTOA-TR-100",
        price_eur: 22,
        weight_grams: 100,
        format: "tranches_100g",
        initial_stock: 30,
      },
    ],
    details: {
      aging_months: 24,
      origin: "Pays Basque",
      breed: "Kintoa",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "fresh",
      conservation_days_after_opening: 30,
      ddm_days: 60,
      cure_method: "Sel sec de Salies-de-Béarn",
      pairings_tags: ["irouleguy", "vin-rouge"],
      seo_title: "Jambon Kintoa AOC 24 mois | Race basque | Lehena",
      seo_description:
        "Jambon de Kintoa AOC affiné 24 mois. Race basque autrefois menacée, élevée en plein air. Sans nitrite. Pièce rare.",
      og_image_url: null,
      noindex: false,
    },
  },
  {
    handle: "jambon-bigorre-noir",
    title: "Jambon Noir de Bigorre 20 mois",
    subtitle: "Race Bigorre · sans nitrite",
    description:
      "Cochon Noir de Bigorre élevé en liberté au piémont pyrénéen. Gras crémeux, viande sombre, persillage très fin. Affinage 20 mois.",
    product_type: "alimentaire",
    shipping_kind: "fresh",
    category_handles: ["jambons-iparralde/orhi-entier", "jambons-iparralde"],
    variants: [
      {
        title: "Entier avec os",
        sku: "BIGO-ENT-OS",
        price_eur: 395,
        weight_grams: 7200,
        format: "entier_os",
        initial_stock: 5,
      },
      {
        title: "Tranches 100g",
        sku: "BIGO-TR-100",
        price_eur: 19,
        weight_grams: 100,
        format: "tranches_100g",
        initial_stock: 40,
      },
    ],
    details: {
      aging_months: 20,
      origin: "Sud-Ouest",
      breed: "Bigorre",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "fresh",
      conservation_days_after_opening: 30,
      ddm_days: 60,
      cure_method: "Sel sec",
      seo_title: "Jambon Noir de Bigorre 20 mois sans nitrite | Lehena",
      seo_description:
        "Jambon de Noir de Bigorre, race rare élevée au piémont pyrénéen, affiné 20 mois sans nitrite. Lehena.",
      og_image_url: null,
      noindex: false,
    },
  },
]

// ─── Salaisons (6 produits) ──────────────────────────────────────────

const SALAISONS: ProductSeed[] = [
  {
    handle: "ventreche-roulee",
    title: "Ventrêche roulée 6 mois",
    subtitle: "Poitrine séchée · sans nitrite",
    description:
      "Poitrine de porc Duroc roulée et séchée 6 mois. Tranchez fin pour l'apéro ou en lardons pour vos plats. Sans nitrite, sel de Salies.",
    product_type: "alimentaire",
    shipping_kind: "fresh",
    category_handles: ["salaisons/ventreches", "salaisons"],
    variants: [
      {
        title: "Entière 1kg",
        sku: "VENT-ENT-1KG",
        price_eur: 38,
        weight_grams: 1000,
        format: "piece",
        initial_stock: 25,
      },
      {
        title: "Demie 500g",
        sku: "VENT-DEMI-500",
        price_eur: 22,
        weight_grams: 500,
        format: "demi",
        initial_stock: 30,
      },
      {
        title: "Tranches 100g",
        sku: "VENT-TR-100",
        price_eur: 6.5,
        weight_grams: 100,
        format: "tranches_100g",
        initial_stock: 80,
      },
    ],
    details: {
      aging_months: 6,
      origin: "Pays Basque",
      breed: "Duroc",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "fresh",
      ddm_days: 45,
      ingredients: "Poitrine de porc Duroc, sel de Salies-de-Béarn, poivre.",
      seo_title: "Ventrêche roulée sans nitrite | Lehena",
      seo_description:
        "Ventrêche de porc Duroc séchée et roulée 6 mois. Sans nitrite. Format entier, demi ou tranches.",
      og_image_url: null,
      noindex: false,
    },
  },
  {
    handle: "saucisson-sec-pays-basque",
    title: "Saucisson sec du Pays Basque",
    subtitle: "Séchage long · sans nitrite",
    description:
      "Notre saucisson sec emblématique. Viande de Duroc, poivre, sel de Salies. Séchage long sans accélérateur ni nitrite. Mâche dense, parfum profond.",
    product_type: "alimentaire",
    shipping_kind: "ambient",
    category_handles: ["salaisons/secs", "salaisons"],
    variants: [
      {
        title: "Pièce 250g",
        sku: "SAUC-250",
        price_eur: 12,
        weight_grams: 250,
        format: "piece",
        initial_stock: 60,
      },
      {
        title: "Tranches 100g",
        sku: "SAUC-TR-100",
        price_eur: 7,
        weight_grams: 100,
        format: "tranches_100g",
        initial_stock: 80,
      },
    ],
    details: {
      origin: "Pays Basque",
      breed: "Duroc",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "ambient",
      conservation_days_after_opening: 21,
      ddm_days: 120,
      ingredients: "Porc Duroc, sel de Salies-de-Béarn, poivre, ail.",
      seo_title: "Saucisson sec Pays Basque sans nitrite | Lehena",
      seo_description:
        "Saucisson sec artisanal du Pays Basque, race Duroc, sans nitrite. Séchage long traditionnel.",
      og_image_url: null,
      noindex: false,
    },
  },
  {
    handle: "chorizo-doux",
    title: "Chorizo doux du Pays Basque",
    description:
      "Saucisson au piment d'Espelette AOP, doux et fumé. Idéal en tapas, à la planche ou dans une piperade.",
    product_type: "alimentaire",
    shipping_kind: "ambient",
    category_handles: ["salaisons/secs", "salaisons"],
    variants: [
      {
        title: "Pièce 250g",
        sku: "CHOR-DOUX-250",
        price_eur: 13,
        weight_grams: 250,
        format: "piece",
        initial_stock: 50,
      },
      {
        title: "Tranches 100g",
        sku: "CHOR-DOUX-TR-100",
        price_eur: 8,
        weight_grams: 100,
        format: "tranches_100g",
        initial_stock: 70,
      },
    ],
    details: {
      origin: "Pays Basque",
      breed: "Duroc",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "ambient",
      ddm_days: 90,
      ingredients: "Porc Duroc, sel de Salies, piment d'Espelette AOP, ail.",
      pairings_tags: ["piment-espelette", "irouleguy"],
      seo_title: "Chorizo doux au piment d'Espelette AOP | Lehena",
      seo_description:
        "Chorizo doux artisanal au piment d'Espelette AOP, sans nitrite. Saucisson basque idéal en tapas.",
      og_image_url: null,
      noindex: false,
    },
  },
  {
    handle: "coppa-traditionnelle",
    title: "Coppa traditionnelle",
    description:
      "Échine de porc séchée et roulée, poivrée, affinée 4 mois. Tranches fines à l'apéritif.",
    product_type: "alimentaire",
    shipping_kind: "fresh",
    category_handles: ["salaisons/secs", "salaisons"],
    variants: [
      {
        title: "Pièce 500g",
        sku: "COPPA-500",
        price_eur: 28,
        weight_grams: 500,
        format: "piece",
        initial_stock: 25,
      },
      {
        title: "Tranches 100g",
        sku: "COPPA-TR-100",
        price_eur: 9,
        weight_grams: 100,
        format: "tranches_100g",
        initial_stock: 50,
      },
    ],
    details: {
      aging_months: 4,
      origin: "Pays Basque",
      breed: "Duroc",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "fresh",
      ddm_days: 45,
      ingredients: "Échine de porc Duroc, sel de Salies, poivre.",
      seo_title: "Coppa traditionnelle Pays Basque | Lehena",
      seo_description:
        "Coppa de porc Duroc séchée 4 mois sans nitrite. À l'apéritif, en planche ou dans une salade.",
      og_image_url: null,
      noindex: false,
    },
  },
  {
    handle: "lonzo-basque",
    title: "Lonzo basque",
    description:
      "Filet de porc séché entier, doux et tendre. Le caviar des salaisons. À déguster en tranches très fines.",
    product_type: "alimentaire",
    shipping_kind: "fresh",
    category_handles: ["salaisons/secs", "salaisons"],
    variants: [
      {
        title: "Pièce 400g",
        sku: "LONZO-400",
        price_eur: 34,
        weight_grams: 400,
        format: "piece",
        initial_stock: 20,
      },
      {
        title: "Tranches 100g",
        sku: "LONZO-TR-100",
        price_eur: 11,
        weight_grams: 100,
        format: "tranches_100g",
        initial_stock: 40,
      },
    ],
    details: {
      aging_months: 5,
      origin: "Pays Basque",
      breed: "Duroc",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "fresh",
      ddm_days: 45,
      ingredients: "Filet de porc Duroc, sel de Salies, poivre.",
      seo_title: "Lonzo basque traditionnel sans nitrite | Lehena",
      seo_description:
        "Lonzo, filet de porc séché 5 mois, sans nitrite. Tendreté exceptionnelle, parfum subtil. Lehena.",
      og_image_url: null,
      noindex: false,
    },
  },
  {
    handle: "lard-sec-poivre",
    title: "Lard sec au poivre",
    description:
      "Lard de poitrine pressé, frotté au poivre noir et séché. Idéal en cuisine ou tranché à l'apéritif.",
    product_type: "alimentaire",
    shipping_kind: "ambient",
    category_handles: ["salaisons/ventreches", "salaisons"],
    variants: [
      {
        title: "Pièce 500g",
        sku: "LARD-500",
        price_eur: 17,
        weight_grams: 500,
        format: "piece",
        initial_stock: 35,
      },
    ],
    details: {
      aging_months: 3,
      origin: "Pays Basque",
      breed: "Duroc",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "ambient",
      ddm_days: 90,
      ingredients: "Poitrine de porc Duroc, sel de Salies, poivre noir.",
      seo_title: "Lard sec au poivre Pays Basque | Lehena",
      seo_description:
        "Lard de poitrine pressé et frotté au poivre, séché 3 mois. Sans nitrite. Pour la cuisine et l'apéro.",
      og_image_url: null,
      noindex: false,
    },
  },
]

// ─── Patxaran & spiritueux (3 produits) ──────────────────────────────

const PATXARAN: ProductSeed[] = [
  {
    handle: "patxaran-traditionnel-50cl",
    title: "Patxaran des Laminak 50cl",
    subtitle: "Recette traditionnelle basque",
    description:
      "Notre patxaran maison, infusé avec prunelles sauvages cueillies au pied des Pyrénées et anis vert. Mûri 6 mois en bonbonne. À déguster glacé en digestif ou en spritz.",
    product_type: "alimentaire",
    shipping_kind: "ambient",
    category_handles: ["patxaran-spiritueux"],
    variants: [
      {
        title: "Bouteille 50cl",
        sku: "PATX-TRAD-50",
        price_eur: 26,
        weight_grams: 850,
        format: "bouteille_500ml",
        initial_stock: 80,
      },
    ],
    details: {
      origin: "Pays Basque",
      allergens: [],
      nitrite_free: false,
      conservation_temp: "ambient",
      ddm_days: 730,
      ingredients: "Eau-de-vie d'anis (50%), prunelles sauvages, sucre.",
      pairings_tags: ["chorizo-doux", "fromage-brebis"],
      seo_title: "Patxaran traditionnel 50cl maison | Lehena",
      seo_description:
        "Patxaran maison Lehena, prunelles sauvages et anis, recette traditionnelle des Laminak. Bouteille 50cl.",
      og_image_url: null,
      noindex: false,
    },
  },
  {
    handle: "patxaran-reserve-70cl",
    title: "Patxaran Réserve 70cl",
    subtitle: "Vieillissement long",
    description:
      "Cuvée spéciale, vieillie 18 mois pour plus de rondeur et de notes confites. Format 70cl, idéal en cadeau.",
    product_type: "alimentaire",
    shipping_kind: "ambient",
    category_handles: ["patxaran-spiritueux"],
    variants: [
      {
        title: "Bouteille 70cl",
        sku: "PATX-RESERVE-70",
        price_eur: 42,
        weight_grams: 1200,
        format: "bouteille_700ml",
        initial_stock: 40,
      },
    ],
    details: {
      origin: "Pays Basque",
      allergens: [],
      nitrite_free: false,
      conservation_temp: "ambient",
      ddm_days: 1095,
      ingredients: "Eau-de-vie d'anis, prunelles sauvages, sucre.",
      seo_title: "Patxaran Réserve 70cl 18 mois | Lehena",
      seo_description:
        "Cuvée Réserve du patxaran Lehena, vieillie 18 mois, format 70cl. Notes confites, rondeur. Idéal cadeau.",
      og_image_url: null,
      noindex: false,
    },
  },
  {
    handle: "eau-de-vie-poire-50cl",
    title: "Eau-de-vie de poire 50cl",
    description:
      "Distillation artisanale de poires Williams. Notes franches et nettes, idéal en digestif.",
    product_type: "alimentaire",
    shipping_kind: "ambient",
    category_handles: ["patxaran-spiritueux"],
    variants: [
      {
        title: "Bouteille 50cl",
        sku: "EAU-POIRE-50",
        price_eur: 38,
        weight_grams: 800,
        format: "bouteille_500ml",
        initial_stock: 30,
      },
    ],
    details: {
      origin: "Sud-Ouest",
      allergens: [],
      nitrite_free: false,
      conservation_temp: "ambient",
      ddm_days: 1825,
      ingredients: "Distillat de poires Williams (40%).",
      seo_title: "Eau-de-vie de poire Williams 50cl | Lehena",
      seo_description:
        "Eau-de-vie de poire Williams, distillation artisanale. Format 50cl. À déguster glacée en digestif.",
      og_image_url: null,
      noindex: false,
    },
  },
]

// ─── Épicerie fine (6 produits) ──────────────────────────────────────

const EPICERIE: ProductSeed[] = [
  {
    handle: "piment-espelette-aop-poudre",
    title: "Piment d'Espelette AOP en poudre",
    description:
      "Le piment d'Espelette AOP, séché et moulu au moulin de pierre. Récolte de l'année précédente, conservée à l'abri de la lumière. Pouvoir piquant moyen, parfum solaire.",
    product_type: "alimentaire",
    shipping_kind: "ambient",
    category_handles: ["epicerie-fine"],
    variants: [
      {
        title: "Pot 40g",
        sku: "ESPE-POT-40",
        price_eur: 9,
        weight_grams: 60,
        format: "pot_180g",
        initial_stock: 200,
      },
    ],
    details: {
      origin: "Pays Basque",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "ambient",
      ddm_days: 730,
      ingredients: "Piment d'Espelette AOP (100%).",
      seo_title: "Piment d'Espelette AOP en poudre · pot 40g | Lehena",
      seo_description:
        "Piment d'Espelette AOP en poudre, pot 40g. Séché et moulu au moulin de pierre. Pouvoir piquant moyen.",
      og_image_url: null,
      noindex: false,
    },
  },
  {
    handle: "piment-espelette-entier-cordon",
    title: "Cordon de piments d'Espelette AOP",
    description:
      "Tresse traditionnelle de piments d'Espelette AOP entiers. Décoratif et culinaire.",
    product_type: "alimentaire",
    shipping_kind: "ambient",
    category_handles: ["epicerie-fine"],
    variants: [
      {
        title: "Cordon 8 piments",
        sku: "ESPE-CORD-8",
        price_eur: 18,
        weight_grams: 250,
        format: "piece",
        initial_stock: 60,
      },
    ],
    details: {
      origin: "Pays Basque",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "ambient",
      ddm_days: 365,
      ingredients: "Piment d'Espelette AOP entier (100%).",
      seo_title: "Cordon de piments d'Espelette AOP | Lehena",
      seo_description:
        "Tresse de piments d'Espelette AOP entiers, présentation traditionnelle décorative et culinaire.",
      og_image_url: null,
      noindex: false,
    },
  },
  {
    handle: "sel-salies-de-bearn-250g",
    title: "Sel de Salies-de-Béarn 250g",
    description:
      "Le sel emblématique de notre terroir, qui assaisonne tous nos jambons. Sel sec à grain fin.",
    product_type: "alimentaire",
    shipping_kind: "ambient",
    category_handles: ["epicerie-fine"],
    variants: [
      {
        title: "Sachet 250g",
        sku: "SEL-SAL-250",
        price_eur: 5.5,
        weight_grams: 280,
        format: "sachet_250g",
        initial_stock: 250,
      },
      {
        title: "Sachet 1kg",
        sku: "SEL-SAL-1KG",
        price_eur: 17,
        weight_grams: 1030,
        format: "sachet_500g",
        initial_stock: 100,
      },
    ],
    details: {
      origin: "Sud-Ouest",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "ambient",
      ddm_days: 1825,
      ingredients: "Sel de Salies-de-Béarn (100%).",
      seo_title: "Sel de Salies-de-Béarn 250g & 1kg | Lehena",
      seo_description:
        "Sel de Salies-de-Béarn, le sel sec qui assaisonne nos jambons. Sachet 250g ou 1kg.",
      og_image_url: null,
      noindex: false,
    },
  },
  {
    handle: "piperade-artisanale",
    title: "Piperade artisanale 330g",
    description:
      "Notre piperade mijotée à l'atelier, en bocal verre stérilisé. Tomates, piments doux, oignons et piment d'Espelette.",
    product_type: "alimentaire",
    shipping_kind: "ambient",
    category_handles: ["epicerie-fine"],
    variants: [
      {
        title: "Bocal 330g",
        sku: "PIPE-330",
        price_eur: 7.5,
        weight_grams: 400,
        format: "pot_330g",
        initial_stock: 90,
      },
    ],
    details: {
      origin: "Pays Basque",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "ambient",
      conservation_days_after_opening: 5,
      ddm_days: 540,
      ingredients:
        "Tomates, poivrons verts et rouges, oignons, ail, huile d'olive, sel, piment d'Espelette AOP.",
      seo_title: "Piperade artisanale en bocal 330g | Lehena",
      seo_description:
        "Piperade basque mijotée à l'atelier, bocal 330g. Tomates, poivrons, oignon, piment d'Espelette AOP.",
      og_image_url: null,
      noindex: false,
    },
  },
  {
    handle: "confiture-cerise-noire-itxassou",
    title: "Confiture de cerise noire d'Itxassou",
    description:
      "La fameuse cerise noire d'Itxassou, partenaire incontournable du fromage de brebis et accompagnement idéal du jambon.",
    product_type: "alimentaire",
    shipping_kind: "ambient",
    category_handles: ["epicerie-fine"],
    variants: [
      {
        title: "Pot 180g",
        sku: "CERISE-180",
        price_eur: 8.5,
        weight_grams: 240,
        format: "pot_180g",
        initial_stock: 100,
      },
    ],
    details: {
      origin: "Pays Basque",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "ambient",
      conservation_days_after_opening: 14,
      ddm_days: 540,
      ingredients: "Cerise noire d'Itxassou (55%), sucre, pectine.",
      pairings_tags: ["fromage-brebis", "jambon-orhi-24-mois"],
      seo_title: "Confiture cerise noire d'Itxassou 180g | Lehena",
      seo_description:
        "Confiture artisanale de cerise noire d'Itxassou. Compagne du fromage de brebis et du jambon basque.",
      og_image_url: null,
      noindex: false,
    },
  },
  {
    handle: "huile-olive-aoc",
    title: "Huile d'olive AOC Vallée des Baux 500ml",
    description:
      "Huile d'olive vierge extra de Provence, sélectionnée pour accompagner notre piperade et nos plats cuisinés.",
    product_type: "alimentaire",
    shipping_kind: "ambient",
    category_handles: ["epicerie-fine"],
    variants: [
      {
        title: "Bouteille 500ml",
        sku: "HUILE-AOC-500",
        price_eur: 22,
        weight_grams: 800,
        format: "bouteille_500ml",
        initial_stock: 40,
      },
    ],
    details: {
      origin: "France",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "ambient",
      ddm_days: 730,
      ingredients: "Huile d'olive vierge extra AOC Vallée des Baux (100%).",
      seo_title: "Huile d'olive AOC Vallée des Baux 500ml | Lehena",
      seo_description:
        "Huile d'olive vierge extra AOC Vallée des Baux 500ml. Sélection Lehena pour la cuisine méditerranéenne.",
      og_image_url: null,
      noindex: false,
    },
  },
]

// ─── Plats cuisinés (3 produits) ─────────────────────────────────────

const PLATS: ProductSeed[] = [
  {
    handle: "axoa-de-veau",
    title: "Axoa de veau",
    description:
      "Notre axoa, plat traditionnel basque : veau émincé mijoté longuement avec poivrons d'Anglet et piment d'Espelette.",
    product_type: "alimentaire",
    shipping_kind: "ambient",
    category_handles: ["plats-cuisines"],
    variants: [
      {
        title: "Bocal 400g · 1-2 pers.",
        sku: "AXOA-400",
        price_eur: 14,
        weight_grams: 460,
        format: "boite_400g",
        initial_stock: 60,
      },
    ],
    details: {
      origin: "Pays Basque",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "ambient",
      conservation_days_after_opening: 2,
      ddm_days: 540,
      ingredients:
        "Veau (55%), poivrons doux, oignons, tomates, ail, piment d'Espelette AOP, huile d'olive, sel.",
      seo_title: "Axoa de veau Pays Basque en bocal | Lehena",
      seo_description:
        "Axoa de veau, plat traditionnel basque mijoté à l'atelier. Bocal 400g, 1 à 2 personnes.",
      og_image_url: null,
      noindex: false,
    },
  },
  {
    handle: "poulet-basquaise",
    title: "Poulet basquaise",
    description:
      "Cuisses de poulet fermier mijotées avec la sauce basquaise maison (tomates, poivrons, piment d'Espelette).",
    product_type: "alimentaire",
    shipping_kind: "ambient",
    category_handles: ["plats-cuisines"],
    variants: [
      {
        title: "Bocal 400g · 1-2 pers.",
        sku: "PB-400",
        price_eur: 12,
        weight_grams: 450,
        format: "boite_400g",
        initial_stock: 60,
      },
    ],
    details: {
      origin: "Pays Basque",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "ambient",
      ddm_days: 540,
      ingredients:
        "Poulet fermier (55%), tomates, poivrons, oignons, ail, piment d'Espelette AOP, huile d'olive, sel.",
      seo_title: "Poulet basquaise en bocal artisanal | Lehena",
      seo_description:
        "Poulet basquaise mijoté à l'atelier Lehena, en bocal 400g. Sauce basquaise traditionnelle.",
      og_image_url: null,
      noindex: false,
    },
  },
  {
    handle: "garbure-bearnaise",
    title: "Garbure béarnaise",
    description:
      "La soupe paysanne du Sud-Ouest, riche en chou, haricot tarbais, jarret de porc et confit.",
    product_type: "alimentaire",
    shipping_kind: "ambient",
    category_handles: ["plats-cuisines"],
    variants: [
      {
        title: "Bocal 750ml · 2 pers.",
        sku: "GARB-750",
        price_eur: 15,
        weight_grams: 850,
        format: "boite_400g",
        initial_stock: 40,
      },
    ],
    details: {
      origin: "Sud-Ouest",
      allergens: ["sulfites"],
      nitrite_free: true,
      conservation_temp: "ambient",
      ddm_days: 540,
      ingredients:
        "Bouillon, chou, haricots tarbais, jarret de porc, confit de canard, oignons, ail, sel, sulfites.",
      seo_title: "Garbure béarnaise en bocal 750ml | Lehena",
      seo_description:
        "Garbure béarnaise traditionnelle, soupe paysanne riche en confit et haricots. Bocal 750ml.",
      og_image_url: null,
      noindex: false,
    },
  },
]

// ─── Coffrets cadeaux (3 produits) ───────────────────────────────────

const COFFRETS: ProductSeed[] = [
  {
    handle: "coffret-decouverte",
    title: "Coffret Découverte",
    description:
      "Trois pièces phares Lehena : chorizo doux, ventrêche tranchée 100g, patxaran 50cl. Présenté en boîte cartonnée signée.",
    product_type: "alimentaire",
    shipping_kind: "fresh",
    category_handles: ["coffrets-cadeaux"],
    variants: [
      {
        title: "Coffret 1",
        sku: "COFF-DECOUV",
        price_eur: 49,
        weight_grams: 1200,
        format: "coffret",
        initial_stock: 30,
      },
    ],
    details: {
      origin: "Pays Basque",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "fresh",
      ddm_days: 45,
      ingredients: "Voir les composants individuels du coffret.",
      seo_title: "Coffret cadeau Découverte Pays Basque | Lehena",
      seo_description:
        "Coffret cadeau Lehena : chorizo doux, ventrêche 100g, patxaran 50cl. Présenté en boîte signée.",
      og_image_url: null,
      noindex: false,
    },
  },
  {
    handle: "coffret-tradition",
    title: "Coffret Tradition",
    description:
      "Le coffret signature : Orhi 18 mois tranches 200g, ventrêche entière 500g, saucisson sec, patxaran 50cl, piment d'Espelette AOP.",
    product_type: "alimentaire",
    shipping_kind: "fresh",
    category_handles: ["coffrets-cadeaux"],
    variants: [
      {
        title: "Coffret Tradition",
        sku: "COFF-TRAD",
        price_eur: 95,
        weight_grams: 2200,
        format: "coffret",
        initial_stock: 20,
      },
    ],
    details: {
      origin: "Pays Basque",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "fresh",
      ddm_days: 45,
      ingredients: "Voir les composants individuels du coffret.",
      seo_title: "Coffret cadeau Tradition Lehena Pays Basque",
      seo_description:
        "Coffret Tradition Lehena : tranches Orhi 18 mois, ventrêche, saucisson, patxaran, piment Espelette. Idéal cadeau.",
      og_image_url: null,
      noindex: false,
    },
  },
  {
    handle: "coffret-prestige",
    title: "Coffret Prestige",
    description:
      "L'expérience complète : Orhi 24 mois sur planche (1 demi), planche à jambon, couteau et patxaran Réserve 70cl. Le cadeau d'exception.",
    product_type: "alimentaire",
    shipping_kind: "fresh",
    category_handles: ["coffrets-cadeaux"],
    variants: [
      {
        title: "Coffret Prestige",
        sku: "COFF-PRES",
        price_eur: 380,
        weight_grams: 5000,
        format: "coffret",
        initial_stock: 10,
      },
    ],
    details: {
      origin: "Pays Basque",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "fresh",
      ddm_days: 60,
      ingredients: "Voir les composants individuels du coffret.",
      seo_title: "Coffret Prestige Lehena · Orhi 24 mois + planche",
      seo_description:
        "Coffret Prestige Lehena : demi jambon Orhi 24 mois, planche à jambon, couteau, patxaran Réserve 70cl.",
      og_image_url: null,
      noindex: false,
    },
  },
]

// ─── Accessoires (3 produits) ────────────────────────────────────────

const ACCESSOIRES: ProductSeed[] = [
  {
    handle: "planche-jambon-bois",
    title: "Planche à jambon en hêtre",
    description:
      "Planche en bois de hêtre massif, gravée du logo Lehena. Surface de découpe robuste, dimensions 50 × 25 cm.",
    product_type: "accessoire",
    shipping_kind: "ambient",
    category_handles: ["accessoires"],
    variants: [
      {
        title: "Standard",
        sku: "ACC-PLAN-50",
        price_eur: 65,
        weight_grams: 1800,
        format: "unite",
        initial_stock: 30,
      },
    ],
    details: {
      origin: "France",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "ambient",
      ddm_days: 3650,
      ingredients: "Bois de hêtre massif.",
      seo_title: "Planche à jambon en hêtre 50cm | Lehena",
      seo_description:
        "Planche à jambon en hêtre massif gravée Lehena, 50×25 cm. L'outil pour découper un jambon entier.",
      og_image_url: null,
      noindex: false,
    },
  },
  {
    handle: "support-jambon-metal",
    title: "Support à jambon métal",
    description:
      "Support métallique avec griffe ajustable. Stabilité maximale pour la découpe au couteau.",
    product_type: "accessoire",
    shipping_kind: "ambient",
    category_handles: ["accessoires"],
    variants: [
      {
        title: "Standard",
        sku: "ACC-SUPP",
        price_eur: 85,
        weight_grams: 2200,
        format: "unite",
        initial_stock: 25,
      },
    ],
    details: {
      origin: "Espagne",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "ambient",
      ddm_days: 3650,
      ingredients: "Acier inoxydable.",
      seo_title: "Support à jambon métal avec griffe | Lehena",
      seo_description:
        "Support à jambon métallique avec griffe ajustable, pour découper un jambon entier en toute sécurité.",
      og_image_url: null,
      noindex: false,
    },
  },
  {
    handle: "couteau-jambon",
    title: "Couteau à jambon professionnel",
    description:
      "Lame longue, fine et flexible. Manche en bois. Le couteau dédié aux jambons entiers.",
    product_type: "accessoire",
    shipping_kind: "ambient",
    category_handles: ["accessoires"],
    variants: [
      {
        title: "Lame 30cm",
        sku: "ACC-COUT",
        price_eur: 55,
        weight_grams: 220,
        format: "unite",
        initial_stock: 40,
      },
    ],
    details: {
      origin: "France",
      allergens: [],
      nitrite_free: true,
      conservation_temp: "ambient",
      ddm_days: 3650,
      ingredients: "Acier inoxydable, manche en bois.",
      seo_title: "Couteau à jambon professionnel lame 30cm | Lehena",
      seo_description:
        "Couteau à jambon professionnel, lame fine 30cm flexible. Manche en bois. L'outil indispensable.",
      og_image_url: null,
      noindex: false,
    },
  },
]

export const ALL_PRODUCTS: ProductSeed[] = [
  ...JAMBONS,
  ...SALAISONS,
  ...PATXARAN,
  ...EPICERIE,
  ...PLATS,
  ...COFFRETS,
  ...ACCESSOIRES,
]
